"use client";
import Navbar from "@/components/navbar";
import "./globals.css";
import type { Metadata } from "next";
import { usePathname } from "next/navigation";
import { Inter } from "next/font/google";
import Header from "@/components/header";
import Footer from "@/components/footer";
import { SessionProvider } from "next-auth/react";
import MyApp from "./_app";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="max-h-screen overflow-y-auto">
          <MyApp>
            <div className="flex ">
              <Navbar />
              <div className="flex w-full justify-between">
                <div className="w-[20%]"></div>
                <div className="w-[80%]">{children}</div>
              </div>
            </div>
            <Footer />
          </MyApp>
        </div>
      </body>
    </html>
  );
}
